// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import com.ctre.phoenix6.CANBus;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    /** CANivore bus used by shooter, intake, and other non-drivetrain motors */
    public static final CANBus kCANivoreBus = new CANBus("Carnivore");

    /**
     * DriveTrain constants - CAN IDs 1-20 (reserved range)
     * 4 wheels x 3 motors each (Drive, Steering, Encoder) = 12 IDs
     */
    public static final class DriveTrainConstants {
        // Front Left Module - IDs 1-3
        public static final int FRONT_LEFT_DRIVE_MOTOR = 1;
        public static final int FRONT_LEFT_STEERING_MOTOR = 2;
        public static final int FRONT_LEFT_ENCODER = 3;

        // Front Right Module - IDs 4-6
        public static final int FRONT_RIGHT_DRIVE_MOTOR = 4;
        public static final int FRONT_RIGHT_STEERING_MOTOR = 5;
        public static final int FRONT_RIGHT_ENCODER = 6;

        // Back Left Module - IDs 7-9
        public static final int BACK_LEFT_DRIVE_MOTOR = 7;
        public static final int BACK_LEFT_STEERING_MOTOR = 8;
        public static final int BACK_LEFT_ENCODER = 9;

        // Back Right Module - IDs 10-12
        public static final int BACK_RIGHT_DRIVE_MOTOR = 10;
        public static final int BACK_RIGHT_STEERING_MOTOR = 11;
        public static final int BACK_RIGHT_ENCODER = 12;

        // Reserved: IDs 13-20 for future drivetrain additions
    }

    /**
     * Shooting system constants - CAN IDs 21-30 (reserved range)
     * Includes shooter wheels, turret, spinner, and feeder
     */
    public static final class ShootingConstants {
        // Shooter Motors - IDs 21-22
        public static final int SHOOTER_LEFT_MOTOR = 21; // Left shooter wheel
        public static final int SHOOTER_RIGHT_MOTOR = 22; // Right shooter wheel

        // Turret Motor - ID 23
        public static final int TURRET_MOTOR = 23; // Turret rotation

        // Feeder Motor - ID 24
        public static final int FEEDER_MOTOR = 24; // Feeds notes to shooter

        // Spinner/Indexer Motor - ID 25
        public static final int SPINNER_MOTOR = 25; // Spins/indexes notes

        // Hood Servo - PWM port 0
        public static final int HOOD_SERVO = 0; // Hood angle servo (PWM)

        // Hood servo limits
        public static final double HOOD_MIN = 0.0;
        public static final double HOOD_MAX = 1.0;

        // Reserved: IDs 26-30 for future shooting system additions
    }

    /**
     * Intake system constants - CAN IDs 31-40 (reserved range)
     * Includes intake rollers and deployment mechanism
     */
    public static final class IntakeConstants {
        // Intake Roller Motors - IDs 31-32
        public static final int INTAKE_LEFT_MOTOR = 31; // Left intake roller
        public static final int INTAKE_RIGHT_MOTOR = 32; // Right intake roller

        // Intake Deployment Motor - ID 33
        public static final int DEPLOY_LEFT_MOTOR = 33; // Moves intake in/out
        public static final int DEPLOY_RIGHT_MOTOR = 34; // Moves intake in/out
        // Reserved: IDs 34-40 for future intake additions
    }

    /**
     * Climber system constants - CAN IDs 41-50 (reserved range)
     * Includes climb motors, elevator, and servos
     */
    public static final class ClimberConstants {
        // Climb/Twist Motors - IDs 41-42
        public static final int CLIMB_LEFT_MOTOR = 41; // Left climb/twist motor
        public static final int CLIMB_RIGHT_MOTOR = 42; // Right climb/twist motor

        // Elevator Motor - ID 43
        public static final int ELEVATOR_MOTOR = 43; // Elevator lift motor

        // Servo IDs (through PWM, not CAN) - PWM ports 1-2
        public static final int CLIMB_SERVO_LEFT = 1; // Left climb servo (PWM)
        public static final int CLIMB_SERVO_RIGHT = 2; // Right climb servo (PWM)

        // Reserved: IDs 44-50 for future climber additions
    }

    public static final class FieldConstants {

        public static final double FIELD_LENGTH_METERS = 16.54;

        // Blue alliance hub — 158.6in (4.03m) from alliance wall to near face of hub
        // Hub is 47in (1.19m) deep, so center is at 4.03 + 0.595 = 4.625m
        public static final Pose2d BLUE_HUB_POSE = new Pose2d(4.625, 4.04, new Rotation2d());
        // Red alliance hub — mirrored across field center
        public static final Pose2d RED_HUB_POSE = new Pose2d(
            FIELD_LENGTH_METERS - 4.625, 4.04, new Rotation2d());

        // TBD
        // public static final Pose2d LEFT_POSE =
        // new Pose2d(16.54, 5.55, new Rotation2d());

        // public static final Pose2d RIGHT_POSE =
        // new Pose2d(16.54, 5.55, new Rotation2d());
    }

}