package frc.robot;

import com.ctre.phoenix6.CANBus;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;

/**
 * All robot-wide constants live here — CAN IDs, PWM ports, field positions, etc.
 *
 * WHY: Keeping all "magic numbers" in one file makes it easy to change wiring
 * or field measurements without hunting through every subsystem file.
 *
 * CAN ID RANGES (so we don't accidentally reuse an ID):
 *   1-20  = Drivetrain (swerve modules)
 *   21-30 = Shooting system (flywheels, turret, feeder, indexer)
 *   31-40 = Intake system (rollers, deploy motors)
 *   41-50 = Climber system (climb motors, elevator)
 */
public class Constants {

    /**
     * The name of our CANivore bus. All non-drivetrain motors are on this bus.
     * The drivetrain uses its own CAN bus configured in TunerConstants.
     * If you plug a motor into the wrong bus, it won't show up!
     */
    public static final CANBus kCANivoreBus = new CANBus("Carnivore");

    /**
     * Drivetrain CAN IDs — each swerve module has 3 devices:
     *   - Drive motor (spins the wheel)
     *   - Steering motor (turns the wheel left/right)
     *   - Encoder (tells us which direction the wheel is pointing)
     *
     * NOTE: These IDs must match what's in TunerConstants.java (generated by Tuner X).
     * If you re-generate TunerConstants, make sure these still match.
     */
    public static final class DriveTrainConstants {
        // Front Left Module
        public static final int FRONT_LEFT_DRIVE_MOTOR = 1;
        public static final int FRONT_LEFT_STEERING_MOTOR = 2;
        public static final int FRONT_LEFT_ENCODER = 3;

        // Front Right Module
        public static final int FRONT_RIGHT_DRIVE_MOTOR = 4;
        public static final int FRONT_RIGHT_STEERING_MOTOR = 5;
        public static final int FRONT_RIGHT_ENCODER = 6;

        // Back Left Module
        public static final int BACK_LEFT_DRIVE_MOTOR = 7;
        public static final int BACK_LEFT_STEERING_MOTOR = 8;
        public static final int BACK_LEFT_ENCODER = 9;

        // Back Right Module
        public static final int BACK_RIGHT_DRIVE_MOTOR = 10;
        public static final int BACK_RIGHT_STEERING_MOTOR = 11;
        public static final int BACK_RIGHT_ENCODER = 12;
    }

    /**
     * Shooting system CAN IDs and settings.
     * The shooter has: two flywheel motors, a turret motor, a feeder motor,
     * an indexer/spinner motor, and a hood servo (on PWM, not CAN).
     */
    public static final class ShootingConstants {
        public static final int SHOOTER_LEFT_MOTOR = 21;  // Left flywheel
        public static final int SHOOTER_RIGHT_MOTOR = 22; // Right flywheel
        public static final int TURRET_MOTOR = 23;        // Rotates the whole shooter
        public static final int FEEDER_MOTOR = 24;        // Pushes notes into flywheels
        public static final int SPINNER_MOTOR = 25;       // Indexes/queues notes

        // Hood servo is on PWM port 0 (not CAN — it's a simple servo)
        public static final int HOOD_SERVO = 0;

        // Hood servo travel limits (0.0 = flat, 1.0 = max angle up)
        public static final double HOOD_MIN = 0.0;
        public static final double HOOD_MAX = 1.0;
    }

    /**
     * Intake system CAN IDs.
     * The intake has: two roller motors (spin to grab notes) and
     * two deploy motors (swing the intake out from the robot frame).
     */
    public static final class IntakeConstants {
        public static final int INTAKE_LEFT_MOTOR = 31;  // Left roller
        public static final int INTAKE_RIGHT_MOTOR = 32; // Right roller
        public static final int DEPLOY_LEFT_MOTOR = 33;  // Swings intake out/in
        public static final int DEPLOY_RIGHT_MOTOR = 34; // Swings intake out/in
    }

    /**
     * Climber system CAN IDs and PWM ports.
     * The climber has: two climb motors, an elevator motor, and two servos.
     * NOTE: Not wired yet — these IDs are reserved for when we build it.
     */
    public static final class ClimberConstants {
        public static final int CLIMB_LEFT_MOTOR = 41;
        public static final int CLIMB_RIGHT_MOTOR = 42;
        public static final int ELEVATOR_MOTOR = 43;

        // Servos use PWM ports (not CAN IDs)
        // public static final int CLIMB_SERVO_LEFT = 1;
        // public static final int CLIMB_SERVO_RIGHT = 2;
        public static final int ELEVATOR_SERVO = 1;

    }

    /**
     * Field positions and zones used for auto-aiming.
     * All positions are in meters, using the WPILib "blue origin" coordinate system:
     *   - (0, 0) is the bottom-left corner when looking from the blue alliance wall
     *   - X increases toward the red alliance wall
     *   - Y increases toward the left (from blue's perspective)
     *
     * FIELD ZONES (2026 REBUILT):
     *   Blue Alliance Zone:  X = 0 to 4.03m
     *   Neutral Zone:        X = 4.03m to 12.51m (includes trenches at the boundaries)
     *   Red Alliance Zone:   X = 12.51m to 16.54m
     *
     * TRENCH: 22.25in (56.5cm) clearance — hood must be flat to fit under.
     *   Trenches run along the guardrails at the boundary between alliance zones
     *   and the neutral zone (near the BUMPs at ~4.03m from each wall).
     */
    public static final class FieldConstants {
        // Total field length in meters
        public static final double FIELD_LENGTH_METERS = 16.54;

        // ===== ZONE BOUNDARIES (X coordinates, blue origin) =====
        // Alliance zone depth from the game manual: 158.6in = 4.03m
        public static final double ALLIANCE_ZONE_DEPTH = 4.03;
        // Neutral zone starts where alliance zone ends
        public static final double BLUE_ZONE_END = ALLIANCE_ZONE_DEPTH;           // 4.03m
        public static final double RED_ZONE_START = FIELD_LENGTH_METERS - ALLIANCE_ZONE_DEPTH; // 12.51m

        // Trench buffer — a small zone around the boundary where we flatten the hood
        // to safely pass under the trench (robot length + margin)
        public static final double TRENCH_BUFFER = 1.0; // 1 meter on each side of boundary

        // ===== HUB POSITIONS =====
        // Blue hub center: 158.6in from blue wall + half of 47in hub depth
        public static final Pose2d BLUE_HUB_POSE = new Pose2d(4.625, 4.04, new Rotation2d());
        // Red hub center: mirrored across field center
        public static final Pose2d RED_HUB_POSE = new Pose2d(
            FIELD_LENGTH_METERS - 4.625, 4.04, new Rotation2d());

        // ===== CORNER TARGETS (for shooting from neutral zone / opponent's side) =====
        // When on the opponent's side, we aim at corner targets instead of the hub.
        // Blue corner targets (used when blue alliance is shooting from neutral/red side)
        public static final Pose2d BLUE_CORNER_LEFT  = new Pose2d(3.5, 6.0, new Rotation2d());
        public static final Pose2d BLUE_CORNER_RIGHT = new Pose2d(3.5, 2.0, new Rotation2d());
        // Red corner targets (mirrored)
        public static final Pose2d RED_CORNER_LEFT   = new Pose2d(FIELD_LENGTH_METERS - 3.5, 6.0, new Rotation2d());
        public static final Pose2d RED_CORNER_RIGHT  = new Pose2d(FIELD_LENGTH_METERS - 3.5, 2.0, new Rotation2d());
    }
}
